# Generated by Django 4.2.6 on 2023-10-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usermessage_auther'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botmessage',
            name='data',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='data',
        ),
    ]
